version: '3.9'

services:
  backend:
    image: blockscout/${DOCKER_REPO:-blockscout}:${DOCKER_TAG:-latest}
    pull_policy: always
    restart: always
    stop_grace_period: 5m
    container_name: 'backend'
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - '172.17.0.1:host-gateway'
    env_file:
      - ../envs/common-blockscout.env
      - ../envs/rollup.env
    volumes:
      - ./logs/:/app/logs/
