version: '3.9'

services:
  proxy:
    image: nginx
    container_name: proxy
    extra_hosts:
      - '172.17.0.1:host-gateway'
    volumes:
      - "../proxy:/etc/nginx/templates"
    environment:
      BACK_PROXY_PASS: ${BACK_PROXY_PASS:-http://backend:4000}
      FRONT_PROXY_PASS: ${FRONT_PROXY_PASS:-http://frontend:3000}
    ports:
      - target: 80
        published: {{PORT}} # placeholder for dynamic replacement
      - target: 8080
        published: 8080
      - target: 8081
        published: 8081
